version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: sudo apt-get install libxtst-dev libpng++-dev
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  build_app:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: build

workflows:
  version: 2
  default:
    jobs:
      - install

      - lint:
          requires:
            - install

      - build_app:
          requires:
            - install
